# Generated by Django 3.0.2 on 2020-01-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200111_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='parents',
            name='id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='parents',
        ),
        migrations.AddField(
            model_name='parents',
            name='child',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='man',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='death',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Death'),
        ),
    ]
