# Generated by Django 3.0.2 on 2020-01-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200111_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='man',
            name='id',
        ),
        migrations.RemoveField(
            model_name='woman',
            name='id',
        ),
        migrations.AddField(
            model_name='death',
            name='marriage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Marriage'),
        ),
        migrations.AlterField(
            model_name='man',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Person'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='marriage',
            unique_together={('wife', 'handsom', 'number')},
        ),
    ]
