# Generated by Django 3.0.2 on 2020-01-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_photo_tag_tagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='death',
            name='id',
        ),
        migrations.RemoveField(
            model_name='death',
            name='marriage',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death',
        ),
        migrations.AddField(
            model_name='death',
            name='person',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Person'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Divorce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('marriage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Marriage')),
            ],
        ),
    ]
